COINES_INSTALL_PATH ?= ../../../..

EXAMPLE_FILE = accel_fifo_watermark.c

API_LOCATION ?= ../..

C_SRCS += \
$(API_LOCATION)/bmi090la.c \
$(API_LOCATION)/bmi090lg.c \
../common/common.c

INCLUDEPATHS += \
$(API_LOCATION) \
../common

include $(COINES_INSTALL_PATH)/coines.mk